name: leetcode
description: Leetcode solutions
version: 1.0.0
repository: https://github.com/DmitryBarskov/leetcode

environment:
  sdk: ^3.2.3

dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.9
